server {
    server_name  frankom.top;
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/frankom.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/frankom.top/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    if ($host != frankom.top){
        return 444;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header X-Custom-Header "hello hecker";

        proxy_pass http://api:8000;
    }

	 location /.well-known/ {
        root /var/www/html/;
        index index.html;
	 }

}

server {
    if ($host = frankom.top) {
        return 301 https://$host$request_uri;
    }

    listen 80 default_server;
    listen [::]:80 default_server;
    server_name frankom.top;
    return 444;
}
